type = "directrequest"
schemaVersion = 1
name = "bigchaindb"
externalJobID = "220a1cc9-ca2b-43b6-bc61-34b25568ad92"
contractAddress = "0x02bF4751574882b27d034Fc4F835A30103f8dfd8"
maxTaskDuration = "0s"
observationSource = """
    decode_log   [type="ethabidecodelog"
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type="cborparse" data="$(decode_log.data)"]
    fetch        [type="bridge" name="bigchaindb" requestData="{ \\"id\\": $(jobSpec.externalJobID), \\"data\\": { \\"id\\": $(decode_cbor.id), \\"method\\": $(decode_cbor.method), \\"model\\": $(decode_cbor.model), \\"meta\\": $(decode_cbor.meta), \\"returnAtt\\": $(decode_cbor.returnAtt)}}"]
    encode_data  [type="ethabiencode" abi="(bytes32 requestId, bytes data)" data="{ \\"requestId\\": $(decode_log.requestId), \\"data\\": $(fetch)}"]
    encode_tx    [type="ethabiencode"
                  abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                 ]
    submit_tx    [type="ethtx" to="0x02bF4751574882b27d034Fc4F835A30103f8dfd8" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> encode_data -> encode_tx -> submit_tx
"""